ERROR - 2023-03-08 04:16:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:16:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:20:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:20:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:20:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:20:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:21:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:21:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:25:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:25:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:25:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:25:22 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:25:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:25:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:25:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:25:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:26:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:26:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:26:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:26:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:26:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:26:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:26:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:26:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:26:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:26:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-08 04:27:02 --> Undefined variable $data
in APPPATH\Controllers\Home.php on line 16.
 1 APPPATH\Controllers\Home.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Home.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-08 04:27:03 --> Undefined variable $data
in APPPATH\Controllers\Home.php on line 16.
 1 APPPATH\Controllers\Home.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Home.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-08 04:27:03 --> Undefined variable $data
in APPPATH\Controllers\Home.php on line 16.
 1 APPPATH\Controllers\Home.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Home.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-08 04:27:03 --> Undefined variable $data
in APPPATH\Controllers\Home.php on line 16.
 1 APPPATH\Controllers\Home.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Home.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:27:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:27:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:27:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:27:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:31:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:31:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:31:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:31:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:47:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:47:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:47:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:47:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:49:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:49:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:50:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:50:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:54:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:54:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:57:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:57:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 04:57:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 04:57:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:01:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:01:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-08 05:48:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ftm', 3306, '', 0)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in E:\Azzam\xampp\htdocs\sisdm\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\Azzam\xampp\htdocs\sisdm\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\Azzam\xampp\htdocs\sisdm\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\Azzam\xampp\htdocs\sisdm\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\Azzam\xampp\htdocs\sisdm\app\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
#6 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(934): App\Controllers\Home->index()
#7 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 E:\Azzam\xampp\htdocs\sisdm\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\Azzam\xampp\htdocs\sisdm\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-03-08 05:48:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `device`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
